FROM debian:buster

RUN apt-get -qq update; \
    apt-get install -qqy \
    build-essential \
    gcc-multilib \
    gdb \
    clang \
    python3 \
    python3-docopt \
    ; \
    rm -rf /var/lib/apt/lists/*
